### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by gkc-finn** [c4lmriver/VueMyAdmin#1]
For "npm i" to work, a package.json file is needed.
Seems like you didn't commit that one.

Appreciated!

**Comment by c4lmriver** [comment]
> For "npm i" to work, a package.json file is needed. Seems like you didn't commit that one.
> 
> Appreciated!

Hello, yes you’re right I just noticed it ! I’ll add it as soon as I can today, thanks for noticing.

**Comment by c4lmriver** [comment]
`package.json` file is now available, see last commit.

I'll now close this issue but feel free to re-open one if necessary !
